@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
#@host = puhelinluettelo-fso.onrender.com
@resource = api/persons
@id = 6
GET http://{{host}}/{{resource}}/
###
GET http://{{host}}/{{resource}}/{{id}}
###
GET http://{{host}}/api/info
###
DELETE http://{{host}}/{{resource}}/{{id}}
###
POST http://{{host}}/{{resource}}/
###
POST http://{{host}}/{{resource}}/
Content-Type: application/json

{
  "name": "Setä Samuli",
  "number": "911"
}